"""empty message

Revision ID: 8a3e2924f0e7
Revises: 
Create Date: 2016-12-19 10:23:17.877460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e2924f0e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_path', sa.String(length=128), nullable=False))
    op.add_column('records', sa.Column('file_name', sa.String(length=128), nullable=False))
    op.add_column('records', sa.Column('file_path', sa.String(length=128), nullable=False))
    op.drop_column('records', 'record_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('record_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('records', 'file_path')
    op.drop_column('records', 'file_name')
    op.drop_column('photos', 'file_path')
    # ### end Alembic commands ###
