"""empty message

Revision ID: f5255e2d7621
Revises: 8a3e2924f0e7
Create Date: 2017-01-08 13:30:00.199078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5255e2d7621'
down_revision = '8a3e2924f0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('conf_uuid', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('email_confirmed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    op.drop_column('users', 'conf_uuid')
    # ### end Alembic commands ###
